"""add_exercise_guides_and_vector

Revision ID: 64e8b5403e6e
Revises: a327c2b3b09d
Create Date: 2026-06-24 21:11:03.033066

"""
from typing import Sequence, Union

from alembic import op
import pgvector
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64e8b5403e6e'
down_revision: Union[str, Sequence[str], None] = 'a327c2b3b09d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.create_table('exercise_guides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exercise_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_muscle', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_guides_exercise_name'), 'exercise_guides', ['exercise_name'], unique=True)
    op.create_index(op.f('ix_exercise_guides_id'), 'exercise_guides', ['id'], unique=False)
    op.create_index(op.f('ix_exercise_guides_target_muscle'), 'exercise_guides', ['target_muscle'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercise_guides_target_muscle'), table_name='exercise_guides')
    op.drop_index(op.f('ix_exercise_guides_id'), table_name='exercise_guides')
    op.drop_index(op.f('ix_exercise_guides_exercise_name'), table_name='exercise_guides')
    op.drop_table('exercise_guides')
    # ### end Alembic commands ###
