"""add_profile_fields_to_user

Revision ID: ba90ce55f545
Revises: 10cebea2ee5f
Create Date: 2026-07-22 11:41:20.369226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba90ce55f545'
down_revision: Union[str, Sequence[str], None] = '10cebea2ee5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_unit', sa.String(), server_default='metric', nullable=False))
    op.add_column('users', sa.Column('weight_kg', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('height_cm', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('fitness_goal', sa.String(), nullable=True))
    op.add_column('users', sa.Column('experience_level', sa.String(), nullable=True))
    op.add_column('users', sa.Column('injuries_or_limitations', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'injuries_or_limitations')
    op.drop_column('users', 'experience_level')
    op.drop_column('users', 'fitness_goal')
    op.drop_column('users', 'height_cm')
    op.drop_column('users', 'weight_kg')
    op.drop_column('users', 'preferred_unit')
    # ### end Alembic commands ###
