"""fix duration minutes datatype to integer

Revision ID: dd038ba48b3f
Revises: 127e5c66eca2
Create Date: 2026-05-27 14:39:51.420700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd038ba48b3f'
down_revision: Union[str, Sequence[str], None] = '127e5c66eca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout_sessions', 'duration_minutes',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using="duration_minutes::integer") # <-- TAMBAHKAN BARIS INI!
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout_sessions', 'duration_minutes',
               existing_type=sa.Integer(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
